### ISSUE TITLE
Collada errors

### ISSUE THREAD

**Issue by jmirabel** [laas/romeo#10]
## Problem
I am using this package on two different machines, one of which is virtual. I am having troubles loading the collada files in the virtual machine. Both machine are running the same software.
In the virtual machine, they simply do not appear, without any error messages, whereas on the physical machine, it works perfectly.

## Software
The software I use for visualization is based on OpenSceneGraph. It has a plugin to read collada files. My version of OpenSceneGraph is 3.2.1.

## Solution
The solution that worked for me was to convert them to STL or DAE using meshlab.

**Comment by francois-keith** [comment]
Hi

Could you give us more details on your virtual machine? Ubuntu 12.04 - 14.04 ... / Windows, 32 / 64 bits?
Did you try displaying the Romeo with another viewer (for example, rviz, or meshlab)?

**Comment by jcarpent** [comment]
The problem comes from an incompatibility between OSG and QT4. Collada files do not appear on some machines when OSG is launched along QT application.
